export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const CURRENT_TAP = "CURRENT_TAP";
export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
